{% set name = "oceanspy" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oceanspy-{{ version }}.tar.gz
  sha256: c78b5dcff3d49ca0a97ea380e156e99da935ed6ba6a52411fa582d4b9c509c4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - dask-core
    - xarray >=0.14.1
    - xgcm >=0.2.0

test:
  imports:
    - oceanspy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hainegroup/oceanspy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for easy ocean model data analysis and visualization

extra:
  recipe-maintainers:
    - ocefpaf
    - malmans2
    - ThomasHaine
    - MaceKuailv
    - asiddi24
    - Mikejmnez
