travis:
  secure:
    BINSTAR_TOKEN: RxBY40KNmuv+bNFJv+hVCf7mwsdcLrr3PveN0HkaBeRi6jzADSy9XFXsVQjTtsXgbU7W7WTVwIq1RYu8Zd2/Je+Xna4DPl0NPo0gp7NoY7RIAmt9TgQwch9cKwqWq3D2+t9Nf92flmeoH6LWPDi1H99ylWL3AK8p1u8FdJYkKOku4oW4ENhc/dbGRmc01PxO3CKg99NuaTdk+DZvIU9y+ERNcdu8FRjAcHBRLRO8p/a3lJZJITMQyiYX8bXK82b7TxvmTHpnR9pBlAgpXqOMRZ9lKC+NwdE80i+V/mBIOVms1Aj+EtLPvu2UVhRY5evUJMTlBSgxu2FGBBf8uoIsCVFRPpi48yYkHCHr7ylZyQh/Zrss5aloYj6yaUA0DwRSlhr+bJZU7Esf20EB27m02/mlc5TjBblHvVD3MpdhP34bJvVJyJUSU2E84tzik3yS9g9emU4nMvS6FX8gDFD5Z2d1R0ZqFXm83B/Z3VdhuBdttoPIRAza34fPgB2BlC9QmXuw61NGFo2h26wzSZzRzaak6BrzS3LDqYlJk6lfA8hTR99B2Mc2glpdT4n92ZquzNW0eMRCrOMbOg8JvqM3y0DpDHnzZ+1+Y+AogPeU8Y51flJdNawx5RkQbh9R5DMskXTqGfd7140+bZPxKnhtcqQS5SJ7HWnPxe7NURZKths=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
